### ISSUE TITLE
Lightbulb icon cannot be used as Next action icon

### ISSUE THREAD

**Issue by Doemaas** [gpapp/FreePlaneGTD#100]
macOS 10.14.6, Freeplane 1.7.9/10, FreeplaneGTD 2.1.1-alpha4/2.5.0
Fresh install Freeplane, FreeplaneGTD, restart Freeplane.
Mindmap with GTD settings with icon:idea (lightbulb), generating next action list with Ctrl-H throws error "Trying to reuse icon:idea as 'Next action'"
<img width="856" alt="FreeplaneGTDErrorIconIdea" src="https://user-images.githubusercontent.com/12998944/65076188-c4b58e80-d998-11e9-9402-5a60f82008ff.png">

**Comment by gpapp** [comment]
Seems like the icon is already in use within the map. Could happen if you already have the setting defined on another branch within the same file. 

Please attach a mm that can reproduce the issue. 

Nb. Development of the 2.1 branch is terminated as of 2019/9/14, due to the removal of the core component used for displaying the task list from Java. 
The new display will be created using old-school Java Swing for those who are already on a later version of Java. It will take a long time.

**Comment by Doemaas** [comment]
Created new map with only GTD settings. See attached.
[IconError.mm.zip](https://github.com/gpapp/FreePlaneGTD/files/3623479/IconError.mm.zip)

**Comment by gpapp** [comment]
Thank you for the map! I traced the issue back to an omission in the documentation.

**Comment by gpapp** [comment]
### Icons

The plugin uses a number of pre-set icons to identify the action items, and their properties. These can be changed according to the users liking.

* Icon: Project (default icon: 'list' looks like a checklist) – specifies the grouping node for actions
* Icon: Next action (default icon: 'yes' - looks like !) – specifies the individual actions
* Icon: Today (default icon: 'bookmark' - looks like a star) – specifies the next actions (When property will be ignored on grouping)
* ___Icon: Week (default icon: 'idea' - looks like a lightbulb)– specifies the next actions (When property will be ignored on grouping)___
* Icon: Done (default icon: 'button_ok' - looks like a checkmark)–  Once an item is completed it can be marked as done.
* Icon: Cancel (default icon: 'button_cancel' - looks like a cross)–  Once an item is cancelled it can be marked as cancelled.

To customize these icons you must place a node with the text above anywhere in your map and add a desired icon to that node. I suggest you place it under a "Config" or "Settings" node in the root of the map, so it doesn't get mixed up with the actual map content.
