### ISSUE TITLE
very slow Freeplane startup after installation of addon v2.5 or v3.0

### ISSUE THREAD

**Issue by nnako** [gpapp/FreePlaneGTD#101]
Hi,

I used to use FpGtd v2.0.1 recently but wanted to check for new features in the recent FpGtd-Versions. So I instlalled first v2.5 and then v3.0 onto a recent Fp v1.7.10p01 resp. v1.7.10p07. In any of the version combinations mentioned I see the same effect which I want to describe here.

SETTING

I auto-load a rather large mindmap at Freeplane startup. It is about 1.2 MB large and consists of many nodes in many hierarchical levels. Containing, among others, about 100 nodes which are marked as GTD elements (Icon is an exclamation mark, many nodes use notes to further describe the GTD element).

WHAT I DO

Now, after installing Freeplane in any of the given versions, I first open the large mindmap then go to the AddOns-Settings, choose the respective FpGtd-Addon-MM-file and press Install. After license confirmation and installation, I do the following:

- open up the addon settings and choose for default hide finished tasks and no folding
- press OK within the settings for the settings to be activated
- then quit Freeplane as recommended for the changes to be ready at next startup
- then restart Freeplane which opens my large mindmap (as usual)

WHAT I SEE

After the mindmap is loaded into Freeplane, I am not able to do any action within Freeplane. No menu activity, no mouse usage for moving the mindmap on the screen, nothing at all. not even closing Freeplane has an effect. Freeplane is completely freezed. Opening the TaskManager on my Windows 10 system shows, that "Java(TM) Platform SE binary (32 Bit)", which is Freeplane, uses up about 35% of my CPU constantly, with the CPU fan clearly audible. After waiting for 7 ("seven") minutes, the CPU fan slows down again and I can start using Freeplane and my mindmap again.

After de-installing the FpGtd-Addon and restarting Freplane, the effect is not visible anymore. Only when one of the current versions of FpGtd is installed, this effect takes place as described above.

SUGGESTIONS

There might be some auto-preparations going on inside the FpGtd-Addon at Freeplane-startup which slow down the startup when it is about large mindmaps? Could you stop these? Or make them user configurable?

Would it generally be possible to speed up the mindmap analysis necessary to generate the GTD-list within Freeplane after pressing `<CTRL> + <H>`?

Any help?

**Comment by gpapp** [comment]
thank you for the explanation I will try to fix this bug as soon as possible

**Comment by gpapp** [comment]
The change handler is installed on startup.
The entire map is reparsed on each node modification.
The entire map is reparsed on node editing.
New alpha is released to get rid of these issues.
