### ISSUE TITLE
Next actions window: action text formatting incorrect, newlines & long lines

### ISSUE THREAD

**Issue by Doemaas** [gpapp/FreePlaneGTD#110]
Freeplane 1.7.10, Freeplane GTD+ 3.5.0-alpha2

Actions with newlines and very long text in the body are not correctly formatted in the next actions window. Resizing of the tool panel due to longer texts make the GUI inaccessable and ^-P has to be used to get rid of the tool panel.

<img width="773" alt="afbeelding" src="https://user-images.githubusercontent.com/12998944/71087151-c101f580-219b-11ea-8183-280a7db63d07.png">

results in 

<img width="1078" alt="afbeelding" src="https://user-images.githubusercontent.com/12998944/71087180-d9721000-219b-11ea-82e0-449430e65696.png">

Removing the the longer action results in 

<img width="980" alt="afbeelding" src="https://user-images.githubusercontent.com/12998944/71087276-11795300-219c-11ea-9bc8-1a60b3f73a03.png">

**Comment by gpapp** [comment]
Seems like an iOS issue, for Windows and Linux the sidebar is scrollable.
