### ISSUE TITLE
Freeplane application windows breaks upon attempting to visualize the Tool panel

### ISSUE THREAD

**Issue by nasko** [gpapp/FreePlaneGTD#113]
OS: Windows 10
Java version: 1.8.0_261
Freeplane version: 1.8.8
FreeplaneGTD version: v3.6.0-alpha2

When I try to view the Tool panel (View / Controls / Tool panel), it gets initially displayed, then whenever I move the mouse, the tool panel gets panned to the left entirely, such that only the rightmost 5 pixels are visible, and the whole screen is gray, apart from the toolbars. There's no horizontal scrollbar which I can use to bring the tool panel back in view. Refer to the attached screenshot. 

Even during the 10 seconds while the tool panel was visible I was not able to see any GTD related information in it.

I'm attaching a log file of the Freeplane execution.

[Freeplane_execution.log](https://github.com/gpapp/FreePlaneGTD/files/5364003/Freeplane_execution.log)
![FreeplaneGTD_Problem](https://user-images.githubusercontent.com/283257/95725838-d42d0700-0c80-11eb-88a4-b41e5c92c4a2.png)

**Comment by nasko** [comment]
This is following this comment that I posted on the blog: https://www.itworks.hu/portfolio/freeplane-gtd/#comment-3482

Someone suggested, that the sidebar referred to the original reply to my comment on the blog, was actually the Tool panel, hence my attempt to activate and see it.

**Comment by gpapp** [comment]
Using the same versions for Java and Freeplane on Windows 10, I cannot reproduce the issue.

1.  Please try removing the folder C:\Users\Nasko\AppData\Roaming\Freeplane\1.8.x\compiledscripts and try again!

1. If the problem persists, close all open mindmaps (freeplane always reopens the last mindmaps), and try running Freeplane with an empty map. There might be node in one of the open maps that prevent startup. This should however show up in the logs.

1. If all fails so far, please  create a new profile folder by replacing your current folder in the startup script. In this profile only install FreeplaneGTD+ and try reproducing the problem with a new map created from the  Freeplane template. 

1. If it doesn't work with a clean install and a few nodes like *test 1, than it's something to do with your environment! Make sure you have nothing that interferes with java execution.

1. Try adding elements you use in your maps, to eventually find what kills the add-on.

Once you find the culprit, please reduce the map that kills the add-on to it's bare minimum so I can debug what causes the issue.

**Comment by nasko** [comment]
@gpapp Closing this one, as the issue was resolved the next day after a computer restart. Might be related to a corrupted cash or something.
