### ISSUE TITLE
Bug! Exception in phase ‚Semantic analysis‘ in source unit…. Scripts\EditTas.groovy 

### ISSUE THREAD

**Issue by ThiasmaF** [gpapp/FreePlaneGTD#118]
Hello, 
I used GTD for a long period and it worked well, but with the switch to groovy, something went wrong...
I could fix some problems with freeplane now by installing the new release, but I still habe problems running the addon, although i deinstalled and reinstalled Freeplane and the addon several times.
There is always the same Error: „the lookup for FreeplaneGTD.Editor.ActionEditor caused a failed compilation.
There should not have been any compilation from this  call.“
Does anyone have an idea what i can do?
Because of the "groovy" in the logfile, i guess there is some trouble in the compilation. (See attached error-log.

[2021-11-24 log.txt](https://github.com/gpapp/FreePlaneGTD/files/7594373/2021-11-24.log.txt)

**Comment by gpapp** [comment]
I'm no longer maintaining the project and no longer use it actively, as I moved on from freeplane, so be as precise as you can!

Please provide exact problem description, including: 

* What version you tried?
* If the issue occurs in a specific map, provide a __minimal__ mm that can replicate the issue.

**Comment by ThiasmaF** [comment]
Thx for your reply- i seem to have solved the problem…Verify it and give a statement ***@***.***'t text and drive... Texten beim Fahren tötet! :-(  —> schreib‘ daheim :-)Am 24.11.21 um 11:55 schrieb Gergely Papp
                
            
            
                
                    Von: "Gergely Papp" ***@***.***>Datum: 24. November 2021An: "gpapp/FreePlaneGTD" ***@***.***>Cc: "Author" ***@***.***>,"ThiasmaF" ***@***.***>Betreff: Re: [gpapp/FreePlaneGTD] Bug! Exception in phase ‚Semantic analysis‘ in source unit…. Scripts\EditTas.groovy  (Issue #118)
                
                
I'm no longer maintaining the project and no longer use it actively, as I moved on from freeplane, so be as precise as you can!
Please provide exact problem description, including:

What version you tried?
If the issue occurs in a specific map, provide a minimal mm that can replicate the issue.

**Comment by ThiasmaF** [comment]
Hi,
as stated above, the main problem is solved: I changed the inbox' name with another name. After renaming it again to inbox, it worked again... 
Now there is another item: When changing the properties of a task and saving it, freeplane wants to send a bug report... I keep trying and maybe it is a similar problem... ;-) 
Downloaded today: Freeplane 1.9.11 and GTD-Addon 3.6.0 alpha2
Give me time to try and thx again...! :-)
By the way, where can I send translations (propositions) to?
