### ISSUE TITLE
Distinguish between tasks with no deadline and weekly tasks

### ISSUE THREAD

**Issue by bepolymathe** [gpapp/FreePlaneGTD#123]
Hi @gpapp @nnako 

In my daily use I find it strange that the tasks by due date view shows the tasks without due date as week tasks. Would it be possible for it to display under a subtitle "undated", "inbox" or "unassigned"?

This would be really ideal in terms of planning.

**Comment by gpapp** [comment]
Yes, that's the way the original plugin worked, and I wanted to keep compatibility with it.

I'm not entirely sure why this was done this way. Maybe because, as per the GTD practice, you should overview all the tasks weekly, so you should be able to assign the due date to those that are pending. So, anything without a date is to be done within a week.

Nevertheless, I may consider this in some release down the road, as I don't really worry about compatibility with the original one anymore.

**Comment by bepolymathe** [comment]
Hi @gpapp 

Thank you for your positive response. In my case, I do a review every week but just decide which tasks become activated... and therefore those that are not activated seem to me more in their place in a sort of "inbox".

Moreover, another behavior seems surprising to me but maybe it is the same explanation. I tend to think that the "wait until date" option should allow the task to appear in the due date tab only from the selected date 🤔

**Comment by gpapp** [comment]
The original plugin used "Today" "This week" and future dates for organization. 

"Wait until" is a different case. That's waiting for a third party specified in the "Wait For". The date is there, so you know when you can expect the results, that you are going to build on.

I could think of adding a HideUntil property as an alternative, but that would also spring into other ideas, like dependency management (e.g. Hide until linked nodes are done) and circular dependencies, which is not something I would like to dig into. :)

**Comment by bepolymathe** [comment]
All right. Thank you for the clarification. It's true that the "wait until" function is already very useful in the current state and I understand that going towards a HideUntil solution is time consuming. If already the tasks without date do not appear any more in the tasks of the week I will be very happy! Thanks to you.

**Comment by bepolymathe** [comment]
Hi @gpapp 

> If already the tasks without date do not appear any more in the tasks of the week I will be very happy! Thanks to you.

I hope you are well. I just wanted to know if you found some time to fit this in?

**Comment by bepolymathe** [comment]
Hi @gpapp 

Thanks for this new release ! After a quick test i have this error 

![image](https://user-images.githubusercontent.com/29939805/235431272-fb66dd14-e7ac-4856-ac77-82fefa67bdaa.png)

![image](https://user-images.githubusercontent.com/29939805/235431348-4ccc40b7-7647-49c4-aab3-cfd7d178c0f7.png)
