### ISSUE TITLE
Exception in phase 'semantic analysis'

### ISSUE THREAD

**Issue by webdb22** [gpapp/FreePlaneGTD#130]
I've just updated to the most recent versions of FreePlane (1.11.1) and GTD (3.8)

As soon as I try to update a node with GTD using "F4" I get an error (see log attached). Based on the log, this seems to be an issue with security settings, although I've explicitly allowed "Script execution" and "Permit file read operation" in "Tools | Preferences | Plugins"

[log.0.txt](https://github.com/gpapp/FreePlaneGTD/files/11407012/log.0.txt)

**Comment by gpapp** [comment]
Based on the log, the recent freeplane seems to have removed or renamed the org.freeplane.core.ui.components.MultipleImage class,so compilation fails.
That's used to display icons on the view.
If you want to use it, please stick to a lower version of freeplane. I'm not sure I will have any time to fix this anytime soon.

**Comment by webdb22** [comment]
@gpapp Thanks for promptly looking into, your analysis and recommendation!

Maybe FreePlane unintentionally dropped this "MultipleImage" class when jumping from 1.10.x to 1.11.x? 

If not, it would be great to have GTD working with FreePlane 1.11.x, maybe you can treat this as an "Enhancement Request" for GTD? Thanks!

**Comment by gpapp** [comment]
Broken by upstream commit:
https://github.com/freeplane/freeplane/commit/336222f87336dd9d835b3beffa6349ff80d157f0
Released a new version 3.8.1, to address the issue.

**Comment by bepolymathe** [comment]
Yes i confirm it works. Thanks you !

**Comment by webdb22** [comment]
@gpapp Thanks for fixing it in no time! Version 3.8.1 works again as expected!
