### ISSUE TITLE
how is a project node defined?

### ISSUE THREAD

**Issue by S4GU4R0** [gpapp/FreePlaneGTD#132]
hey there, 

i am new to this addon, and i appreciate the life it's brought to the previous version. 

i understand that nodes that are considered projects have a list icon attached to the node, but it's not clear to me how to indicate that a node is a project for the addon. i assume i don't manually add the icon based on it being in the config. i don't see anything in the action editor, the docs, or the readme, though i admittedly haven't checked if the old version has its own docs? in the gtd method, a project is defined as a task due within the next 12 months and has multiple subtasks.  but when i set up a structure that meets that definition to test, I don't see anything. i can get the addon to recognize everything else just fine. i am only stuck specifically on how to make a node a "project." 

thanks again.

**Comment by gpapp** [comment]
I am glad you find the addon useful. I've discontinued development about five years ago, and hardly remember how it works anymore. 

Keep it in mind, that this is made using the restrictive addon framework of the mind map editor and only uses the features within to display nodes that are marked with arbitrary icons.

You can open, edit any mindmap without the addon, set your own gtd structure up, and it will display on the sidebar once the addon is installed. 

Everything is up to you. You do not need to use the template, or add a config section, the nodes will be picked up anywhere on the map. If you are happy with the defaults, you don't need to have them defined at all. 

You can have a huge mindmap with some nodes littered around that are marked as tasks and those will be picked up. 

The project here is just a container for tasks. If the task has any nodes above it that has the project icon, it will be added to that project. If a project has any project nodes above it will be the subproject of that. A task can be a project and a task in the same time if that's meaningful for you. 

So go ahead and add the icon manually. It will work. 

See some docs at
https://www.itworks.hu/portfolio/freeplane-gtd/

I hope that helps and you will still get some miles out of this relic!
