### ISSUE TITLE
Script error when using Convert Tasks from short hand

### ISSUE THREAD

**Issue by cleanshaven** [gpapp/FreePlaneGTD#26]
Installed GTD 1.2.  Got the error that is in the attached screen shot
![freeplanegtderror](https://cloud.githubusercontent.com/assets/11422758/6595173/3b59d3d0-c7be-11e4-87ff-53e853a6c44b.PNG)

**Comment by gpapp** [comment]
That was a typo in the release I never bothered to fix, as I didn't know anyone else was interested. If you want to use that version you'd have to modify the line 
```groovy
import FreeplaneGTD.GTDMapreader 
```
line to read
```groovy
import freeplaneGTD.GTDMapreader 
```
somewhere in the begining of the file.

I've got the new version released just to fix this today. It's available at the github release page [here](https://github.com/gpapp/FreePlaneGTD/releases/tag/v1.3)

The release is also available on the [FreeplaneGTD release page](www.itworks.hu/freeplanegtd-release/index.html)

See the [blog post](http://wp.me/p4IsE0-6B) about the current release.

Thank you for the feedback, I also appreciate any kind of feedback, improvement ideas so I can set where I'm going with it! 
Now that I know someone else is also using the addon I'll be more careful with my releases. :-)
