### ISSUE TITLE
availability of GTD v1.4 for Freeplane v1.2.x

### ISSUE THREAD

**Issue by nnako** [gpapp/FreePlaneGTD#31]
Hi.

Thanks for the further development and enhancement of the GTD addon. On Freeplane v1.3.x it plays well as far as I saw it. What about the older Freeplane versions v1.2.x? Will you invest some time to make it available here, too? I still use GTD v0.8 on Freeplane v1.2.x as company restrictions make it hard for me to proceed to Freeplane v1.3.x . Thus, currently I would have to stick to the original v0.8 of the GTD addon.

Do you know, how to "port" GTD to be downward compatible? Maybe I could even support you as a programmer, if you like.

**Comment by gpapp** [comment]
There is no reason it would not work with 1.2, as it uses standard API available in 1.2.

Test it, and if you encounter any errors report it here with the stack trace! (log file from the user's freeplane directory l) 

All contributions are welcome, I'm more than happy to add patches, features or additional  language support!
