### ISSUE TITLE
settings not applicable because of seeming data format mismatch

### ISSUE THREAD

**Issue by nnako** [gpapp/FreePlaneGTD#33]
In order to set / modify the default sorting scheme (Project, Who, Context, Timeline) within the GTD list window, the user can edit the information in the AddOn's settings window by moving into [Tools] > [AddOns] > [Configure]. But no change is accepted due to the following error message:

error message:
![pic__error_message_after_changing_configuration](https://cloud.githubusercontent.com/assets/5845602/9734081/a39f0e3c-5630-11e5-842e-2c364f97646d.png)

I have never changed the default date, time and number format settings by hand. So I don't know how to set these settings in order that the AddOn accepts them.

Here the contents of LOG file (the last paragraph might be the important one):
```
Sep 8, 2015 1:45:20 PM org.freeplane.core.util.LogUtils info
INFO: freeplane_version = 1.3.15; freeplane_xml_version = freeplane 1.3.0
git revision = b0e97d9_dpolivaev_2015-02-071803310100
java_version = 1.6.0_33; os_name = Windows 7; os_version = 6.1
Sep 8, 2015 1:45:25 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date format M/d/yy
Sep 8, 2015 1:45:25 PM org.freeplane.core.util.LogUtils info
INFO: added parsing support for standard date time format M/d/yy h:mm a

STDOUT: Loaded properties from bundle://3:1/org/freeplane/plugin/formula/defaults.properties
STDERR: missing key freeplaneGTD_view_project
STDERR: missing key freeplaneGTD_view_who
STDERR: missing key freeplaneGTD_view_context
STDERR: missing key freeplaneGTD_view_whenSep 8, 2015 1:45:35 PM org.freeplane.core.util.LogUtils info
INFO: extending script's classpath by [C:\PROGS\Freeplane_v1_3_15\Data\Freeplane\1.3.x\lib, C:\PROGS\Freeplane_v1_3_15\Data\Freeplane\1.3.x\lib\flying-saucer-core-9.0.7.jar]

STDOUT: Loaded properties from bundle://6:1/org/freeplane/plugin/script/defaults.propertiesSep 8, 2015 1:45:35 PM org.freeplane.core.util.LogUtils info
INFO: looking for scripts with the following endings: [js, groovy]
Sep 8, 2015 1:45:36 PM org.freeplane.core.util.LogUtils info
INFO: compiled in C:\PROGS\Freeplane_v1_3_15\Data\Freeplane\1.3.x\lib: [ClipBoardUtil.groovy, DateUtil.groovy, GTDMapReader.groovy, ReportModel.groovy, Tag.groovy]

STDOUT: Framework launchedSep 8, 2015 1:45:38 PM org.freeplane.core.util.LogUtils info
INFO: requesting mode: MindMap
Sep 8, 2015 1:45:46 PM org.freeplane.core.util.LogUtils info
INFO: menu items to execute: []
Sep 8, 2015 1:46:11 PM org.freeplane.core.util.LogUtils info
INFO: execute [rundll32, url.dll,FileProtocolHandler, file:/C:/PROGS/Freeplane_v1_3_15/Data/Freeplane/1.3.x/]
Sep 8, 2015 1:46:48 PM org.freeplane.core.util.LogUtils warn

WARNING: Appearance/look_and_feel/lookandfeel not found
Sep 8, 2015 1:46:54 PM org.freeplane.core.util.LogUtils warn
WARNING: <html><body>Validation error(s):<p><em>Invalid standard date format<br>Invalid standard date-time format<br>Invalid standard number format</em><p>Please change the preferences to fix the error(s).</body></html>
Sep 8, 2015 1:46:54 PM org.freeplane.core.util.LogUtils severe
SEVERE: Validation errors: [Invalid standard date format, Invalid standard date-time format, Invalid standard number format], warnings: []
```

**Comment by gpapp** [comment]
This seems to be the problem with Freeplane itself, several add-ons registered the same problem. Freeplane is doing a generic preferences initialization when trying to show the settings for the add-on, and fails.

Please go to Freeplane preferences -> Behaviour and check what's set as the Standard date and number format there. I suspect it has something to do with the operating systems locale settings.

In my case it says 
* standard number format: #0.####
* standard date format: SHORT
* standard date-time format: SHORT, SHORT
* Locale for formats: Automatic

And mine works.

Please note, what are the values in your case, and if they differ, you can set these defaults.

I would like to know these values,  your computer's language and locale settings, for further assistance.

If you can't set these values values, that won't break, you can always access the add-on preference settings from Freeplane preferences -> Plugins -> freeplaneGTD add-on

**Comment by nnako** [comment]
My standard settings within **[Behaviour] > [Data formatting and parsing]** are the same as yours. My computer's language is German and my locale settings (for Freeplane) is currently set to English. Trying different language configurations, I was not yet able to figure out those which would actually work in connection with the addon settings accessible through **[Tools] > [Add-ons] > [Configure]**.
