### ISSUE TITLE
strip off or display HTML content in GTD list

### ISSUE THREAD

**Issue by nnako** [gpapp/FreePlaneGTD#35]
Currently, when the GTD node core or the project description node core consists of HTML-formatted text (e.g. multiline text or colored text), it will be transferred to the GTD list as raw HTML (including tags within angle brackets). This is visible after pressing **``<CTRL> + <H>``** to call the GTD list. So, the task description and/or the project description will appear cryptic within the GTD list. To avoid this, the HTML control characters must be stripped off or evaluated before printout within the GTD list. Maybe configurable by a new option **``display HTML content [YES/NO]``**.

**Comment by gpapp** [comment]
Could use http://freeplane.sourceforge.net/doc/api/org/freeplane/core/util/HtmlUtils.html to strip content, or just display HTML content as HTML.
