### ISSUE TITLE
Dutch translations (issue and resolution).

### ISSUE THREAD

**Issue by Doemaas** [gpapp/FreePlaneGTD#46]
Small contribution of the Dutch translations leaf (.mm in the .zip), didn't know where to put it otherwise. Could someone incorporate this in a future version? Thanks!

[freeplaneGTD-v1.7.0-Dutch-NL-translation.mm.zip](https://github.com/gpapp/FreePlaneGTD/files/134657/freeplaneGTD-v1.7.0-Dutch-NL-translation.mm.zip)

**Comment by gpapp** [comment]
Added to new release #v1.7.1
