### ISSUE TITLE
Error executing the script

### ISSUE THREAD

**Issue by OttKostner** [gpapp/FreePlaneGTD#47]
Trying to run FreePlaneGTD 1.8.0 gives an error: 'Error executing the script: Name is null'

Reverting back to 1.7.1 solves the problem.

![gtd_ 1](https://cloud.githubusercontent.com/assets/14902271/13806119/369659a4-eb62-11e5-990f-5c5e87941abd.png)

![gtd_ 2](https://cloud.githubusercontent.com/assets/14902271/13806289/6dfeab7a-eb63-11e5-87b9-53c7bbc2e73d.png)

**Comment by gpapp** [comment]
Hi
great find! Thanks for testing the new version!

There is a problem with the preference parsing of the initial view at the moment. I'll fix it in a few  days.

If you want to try the new version, you have to go to preferences and select the prefered initial view, or just save the new preferences.

**Comment by Tibi** [comment]
Hi,

I have this exact issue with Java 11. With Java 8 it works.
Freeplane 1.7.3
FreePlaneGTD 2.0.1 or 2.1 alpha4
