### ISSUE TITLE
Error in changing preferences

### ISSUE THREAD

**Issue by OttKostner** [gpapp/FreePlaneGTD#48]
When trying to change preferences (default action Who), Freeplane returns an error:

![gtd_ 3](https://cloud.githubusercontent.com/assets/14902271/13839866/378bb30c-ec27-11e5-8ddf-ff3e0598336a.png)

**Comment by gpapp** [comment]
Known issue with the Freeplane add-on system. Nothing the add-on could fix, should be taken upstream.
