### ISSUE TITLE
By Who does not always work in 1.8.1

### ISSUE THREAD

**Issue by OttKostner** [gpapp/FreePlaneGTD#49]
Test case included:

![gtd_ 5](https://cloud.githubusercontent.com/assets/14902271/13840835/ba8a1342-ec2d-11e5-8068-babe071f0a3a.png)

When going back to 1.7.1 it works with the same setup:

![gtd_ 6](https://cloud.githubusercontent.com/assets/14902271/13840918/6151ad2a-ec2e-11e5-8f1d-677ec41c6719.png)

**Comment by gpapp** [comment]
Seems like the change doesn't work.
Can you attach the logfile, and the sample file?

**Comment by OttKostner** [comment]
Test file included:

[TESTING.zip](https://github.com/gpapp/FreePlaneGTD/files/177844/TESTING.zip)
