### ISSUE TITLE
Actions with newlines results in an error when listed.

### ISSUE THREAD

**Issue by Doemaas** [gpapp/FreePlaneGTD#54]
Ctrl-H on a mindmap with actions containing newlines results in an error displayed:

Can't load the XML resource (using TRaX transformer).
org.xml.sax.SAXParserException; lineNumber: 4; columnNumber: 17; The element type
"br" must be terminated by the matching end-tag "</br>"

Version 1.8.2.

**Comment by gpapp** [comment]
This is obsolate due to the updated HTML display.
