### ISSUE TITLE
Plugin install fails

### ISSUE THREAD

**Issue by sjsrey** [gpapp/FreePlaneGTD#56]
Freeplane version: 1.3.15
FreePlaneGTD version: 1.8.2
OS: Ubuntu Mate: 16.04

![screenshot at 2016-05-02 16 36 04](https://cloud.githubusercontent.com/assets/118042/14971140/692f9e38-1084-11e6-820d-a850353fc617.png)

Possibly related to [this bug](https://sourceforge.net/p/freeplane/bugs/2330/?limit=25)?

**Comment by gpapp** [comment]
Upstream bug,  reported, fixed,  patch provided to Freeplane developers.  

https://sourceforge.net/p/freeplane/bugs/2330/

Please apply the patch manually, until Freeplane is fixed!
