### ISSUE TITLE
Don't show Archived projects in Next Action list

### ISSUE THREAD

**Issue by dvictori** [gpapp/FreePlaneGTD#57]
First, thanks for this great plugin. I'm using to organize my stuff but not sure I'm using it the correct way. When I finish a project (done all actions), I move it to the Archive branch. However, the actions for said project still shows up in the Next Action list. I'd like to have a place to keep track of the completed projects but I don't want it to clutter my Next action list. I could filter the next action by completed tasks but I'd like to see all the tasks (completed or not) of my ongoing projects. Am I using the Archive branch in the wrong way? Is it possible to filter out completed projects, not just the actions?

**Comment by gpapp** [comment]
You are free to use any way you see fit. :)  I'm glad to hear if it helped anyone at all! 

The idea I had when I took over the development of the add-on is to use the icons for marking tasks completed, regardless where it is in the tree.  Any task not marked as done will show up in the action list. You can still see the completed tasks by checking the show completed checkbox on the list.

I never wanted to constrain anyone with forcing a pre-set structure to their thinking. I provide a sample map as a guideline, but the idea of a mindmap is the mapping of the user's mind, not mine. The review and archive branches are proposed to be used with the move to review / archive function (F5 and F6 hotkeys) , that replicates your project structure and moves your tasks to their corresponding projects. (it will also move any project nodes without open tasks or no content)  This is for reducing clutter of the main actions. 

As for now, I'm tied up with other things, so I won't be dealing with it unless  more users  come demanding the feature,but I'm leaving it open, just in case. 

If you need to achieve the same result, you could emulate this behavior by using the archive function, then moving your archived items to a disjunct archive map and linking it to the archive node.

**Comment by dvictori** [comment]
Thanks. Now I understand a bit better how the F5 and F6 keys work. I'll try your suggestion of moving the completed projects to another map
