### ISSUE TITLE
When value only works if is a complete date

### ISSUE THREAD

**Issue by dvictori** [gpapp/FreePlaneGTD#58]
I created an action with the {someday} attribute. The shorthand is processed fine but looking at the Next Action list (CTRL+H), in the timeline option, the action is filed under 'This week' and no 'someday' grouping is available. I can only get the timeline grouping to work if I use a complete date (yyyy-mm-dd)

**Comment by gpapp** [comment]
This works for me. Please include an example and your logfile if the issue persists!

**Comment by dvictori** [comment]
See the attached screenshot. I have 3 forms of when attribute. One is a complete date, one is text and the other, just the year. Looking at the Next action list, only the complete date is separated from the other actions.
![gtd_when_attribute](https://cloud.githubusercontent.com/assets/5786553/20921864/329bb5be-bb8d-11e6-8e39-b0e24b29f944.PNG)

The last log file (log0.txt) is also attached.
[log.0.txt](https://github.com/gpapp/FreePlaneGTD/files/633538/log.0.txt)

I only noticed an error in the log file when I tried to look at the GTD plugin preferences. It mentions "invalid standard date format". That is shown in log.1.txt
[log.1.txt](https://github.com/gpapp/FreePlaneGTD/files/633542/log.1.txt)

I'm using GTD Plugin v 1.8.2 on freeplane 1.5.14 (win10)
Thanks

**Comment by gpapp** [comment]
I see no error in your configuration, however I cannot reproduce it no matter how I tried.

Please try to uninstall the add-on, remove the content of C:\Users\m330625\AppData\Roaming\Freeplane\1.5.x\addons\freeplaneGTD then reinstall it.

If you're at it, you can try version 1.9.0!

![image](https://cloud.githubusercontent.com/assets/4165192/20946148/f78c3322-bc09-11e6-98f2-246086b47ce4.png)

**Comment by dvictori** [comment]
Upgrading to version 1.9.0 fixed it. Thanks for you attention
![freeplane_gtd](https://cloud.githubusercontent.com/assets/5786553/20965706/2a2de18c-bc5e-11e6-8a25-6d3d7527498c.PNG)
