### ISSUE TITLE
Cannot cast object 'class ReportWindow' with class 'java.lang.Class' to class 'ReportWindow'

### ISSUE THREAD

**Issue by pad52** [gpapp/FreePlaneGTD#59]
Error occurs when trying to open 'Next action list'
System is OSX 10.10.5
java version: 1.8.0_91
freeplane: 1.5.17

**Comment by gpapp** [comment]
Somehow it works in my development environment. Will look into it later.

**Comment by gpapp** [comment]
Result of an error in the Freeplane script permission management policy. Release updated, please check again.
