### ISSUE TITLE
Create a sample gtd projecct map to explore functionality?

### ISSUE THREAD

**Issue by LeoStaley** [gpapp/FreePlaneGTD#77]
I love this! Would it be possible for you to create some kind of sample map or tutorial map so a user can explore the functionality provided by FreeplaneGTD+?

**Comment by gpapp** [comment]
It's already done. 
After installing the addon, create a new map from template and select the GTD template.
The created map will show how the addon can be used. Each section is explained in the collapsed  node detail. You can view these explanations by hovering the pointer over the comment icon.

**Comment by LeoStaley** [comment]
I've poured over ever bit of that map, but I still can't figure out how to make an action node. 

If I make a new node under "Inbox", and I try to use "Edit action" on it, it gives me an error message, saying 

>"Selected node is not a task"

....
....
OK, so after some digging, I found some posts on the website explaining how to do it. I think it would be **extraordinarily helpful** to include an additional help.mm mindmap in the addon to explain how to use use it. 

Nowhere in the template did it mention that I needed to put a * at the beginning of a node to make it a task. nor did it explain how to add "when," "contexts," etc.

**Comment by gpapp** [comment]
That's right. I should include the contents of the https://github.com/gpapp/FreePlaneGTD/blob/master/README.md somewhere in the project or maybe a few more links to the project site  https://www.itworks.hu/portfolio/freeplane-gtd/ which is also the only place the installation process is explained. 

Feel free to create such a file and I'm more than happy to post it along with the addon!

Too bad there is no way in opening it automatically after the addon is installed.

**Comment by LeoStaley** [comment]
I will explore about with it, and see what I can do. I already have my own freeplane to-do system that doesn't use any scripts or addons, but I've been looking for ways to improve it. I should be back soon with some more feedback

**Comment by gpapp** [comment]
No response from requester.
