### ISSUE TITLE
make freeplanegtd+ only active for certain maps

### ISSUE THREAD

**Issue by bitclick** [gpapp/FreePlaneGTD#89]
i am using I am using v2.1-alpha-4 in freeplane 1.7.3 on ubuntu 18.04.1 64 bit running on
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**current behavior:**
freeplanegtd+  is **always active in that it listens to map changes** etc..  this leads to errors (triggerd bugs) and sluggish/unwanted behavior on several of my (big) maps that i dont want to use with gtd at all. 

for instance pasted nodes with * at beginning are changed though i dont want it.

**proposed behavior:**
freeplanegtd+ **only listens to certain open maps that are identified by some explicit property**, e.g. an attribute in the root node or a mandatory settings-node with said attribute. 
then the user can activate freeplanegtd+ for a certain map if he wants to use it 

if you point me in a good direction, i can try to help with the implementation (have no experience yet besides small scripts on nodes)

**Comment by gpapp** [comment]
Needs restructuring of the entire add-on.

**Comment by bitclick** [comment]
i see.. i will read trough the code and maybe i can come up with a not-so-invasive compromise..

**Comment by bitclick** [comment]
Just for your information: I now switched away from freeplaneGTD+ to emacs with orgmode. in this state freeplanegtd+ is not really usable for me. for me, orgmode is a different (better) world in nearly every regard, except it has no graphic representation of the projects etc.

maybe i try your project again in a few years..

**Comment by gpapp** [comment]
If it doesn't suit you don't use it. I created this to suit my own needs and shared it with the community. A few dozen users found it useful, so I added some features. It fits my way of work as is, so don't expect much change in it in the upcoming years. Especially since Oracle pulled the plug on JavaFX recently,that's essential for rendering the list. 
You can always grab the code and modify it for your own personal needs.
