### ISSUE TITLE
dont change node's content when GTD icon is present

### ISSUE THREAD

**Issue by nnako** [gpapp/FreePlaneGTD#91]
Currently, when a node contains significant characters, the respective content is automatically fed into the node's attributes like e.g.:

- **[** `<name>` **]**  ->  node's "WHO"-attribute will contain the value of `<name>`
and the bracketed portion will be removed from the node's core
- ...

Now, in my mindmaps I frequently use these special characters within node's core portions for my own purposes. Like in the example, `[` and `]` are used to specify the "source type" or "source" of something, e.g.:

- node's core: "**Presentation of introduction [PPT]**"
means that the file-linked presentation is stored in PPT format

In general, when I want to use this node as a GTD element (indicated by prefixing the node's core with a **STAR** "`*`" character or by adding the respective **GTD ICON** to the node) the GTD node's core will be transformed according to the GTDs concept and special character usage. Which is great, in general.

Now: **Would it be possible to do these modifications of a node's code and attributes ONLY when there was no GTD ICON set?**

This would mean, everything I alter manually in the node's core after the GTD ICON was set, will not be transformed. The node's core and attributes would be left as they are, in order to be printed e.g. within the GTD list displayed using `<CTRL> + <H>`. A user could always still modify the GTD-specific contents associated with the node (manually within the attributes, by using the GTD dialog or automatically by removing the GTD ICON and prefixing a STAR). But once the GTD ICON was set, contents would be stable to facilitate the application of a user's own markup concepts.

What do you think?

**Comment by gpapp** [comment]
This works as intended. It is designed this way to update the attributes. 
You can use the node details to store unparsed data.
