### ISSUE TITLE
Title below tasks

### ISSUE THREAD

**Issue by koekjesdoos** [gpapp/FreePlaneGTD#93]
In Project view:
Title of Project is showing below the tasks from that project.

For the other views same problem i.e
![gtd](https://user-images.githubusercontent.com/1750017/52863359-eebf7d80-3137-11e9-951c-b71e863c7952.png)

**Comment by gpapp** [comment]
Known issue with freeplane 1.7 beta. Fixed in later beta versions.

**Comment by ajeden** [comment]
Stable 1.7.7 has is as well.

**Comment by ajeden** [comment]
If you need a temporary fix, put the Title at the bottom of ReportWindow.groovy/private static String formatList(Map list, Map<String, String> contextIcons, boolean showNotes), so the end of the function looks like:
```
 	Tag title = body.addChild('h2')
            if (contextIcons.keySet().contains(it['title'])) {
                title.addChild('img', [class: "contextTitleIcon", src: getIconCopyURL(contextIcons.get(it['title']) + ".png"), "title": it['title']])
            }
            title.addContent(it['title'] as String)
        }
        html.addContent(body)

        return HTML_HEADER + html.toString()
    }
```

**Comment by gpapp** [comment]
Don't do that, use a later version of the addon which is already fixed.
