### ISSUE TITLE
Add switch to hide details

### ISSUE THREAD

**Issue by ajeden** [gpapp/FreePlaneGTD#94]
Could you please add switch that would hide extra details from the task lists in report window?
instead of:
```
who
     to do for topic {Today}
                                            Select nodes|Copy
who2
     to do 2 for topic {Today}
                                            Select nodes|Copy
```
it would show (and copy):
```
who
      to do
who2
      to do 2
```

PS. Thanks for a great add-on!

**Comment by gpapp** [comment]
The entire idea of the task list is to show all relevant information. 

If you don't want to see data, why put it in the map?

**Comment by ajeden** [comment]
Different usage: I'm capturing my meeting notes. Usually, I only need to put down action list per person for participants and PM to organize further. Thus, I am usually deleting `for ....`, and often end up deleting `{This week}` before sending.

**Comment by gpapp** [comment]
This is a GTD tool for keeping track of one's own tasks and targets not a project management tool. 
You may modify your add-on locally to remove unwanted fields.
