### ISSUE TITLE
list upside down for ver 2.0.1 & move nodes error with ver 2.1.1

### ISSUE THREAD

**Issue by highart** [gpapp/FreePlaneGTD#98]
GTD list  displayed upside down after upgrade FP 1.7.5 or later.
When I press control-H, list is displayed upside down like

  todo
project
  todo
project

I tried beta version and the list displayed correctly but than move node function of FP (control + ARROW keys) works in weird manner. 

Thank you

**Comment by gpapp** [comment]
Fixed in later versions. Move node function of the freeplane application is not related to the addon, please open a ticket upstream.
