### ISSUE TITLE
GTD add-on influence on correct working of Freeplane node movement

### ISSUE THREAD

**Issue by Doemaas** [gpapp/FreePlaneGTD#99]
macOS 10.14.6, Freeplane 1.7.9, FreeplaneGTD 2.1.1-alpha4
Fresh install Freeplane, FreeplaneGTD, restart Freeplane.
Move a node with Cmd-cursorUp, moves the node correctly but sets the focus on the node that was initially below the moved node.
After ^-H (create next action list) and closing the resulting window, restores the correct behaviour: moves the node and sets the focus on that node.
Restart Freeplane and the erronous behaviour is back again until ^-H.
This does not happen without the FreeplaneGTD add-on.

**Comment by gpapp** [comment]
Can't reproduce it on Windows or Linux. Probably a macOS specific issue, without a Mac at hand I can't fix it.

**Comment by Doemaas** [comment]
This is fixed since 3.0-alpha1, not using the JavaFX anymore.
I really like the Tool Panel use of creating the next action list. It's  clean and fast. Thanks Gergely!
